
Running tests...
----------------------------------------------------------------------
E
======================================================================
ERROR [0.002s]: helloworld_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/usr/lib/python3.10/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: helloworld_tests
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/mnt/c/Users/sreek/pyb-dev/src/unittest/python/helloworld_tests.py", line 1, in <module>
    from mockito import mock, verify
ModuleNotFoundError: No module named 'mockito'


----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)

Generating XML reports...
